strongswan_conn_default:
    ikelifetime: 60m
    keylife: 20m
    rekeymargin: 3m
    keyingtries: 1
    keyexchange: ikev2
    authby: secret
strongswan_secrets:
    - right:  "cor-host-dmz"
      left: ""
      type:  PSK
      credentials: '"p455w0rd"'
strongswan_conns:              
    conn1:
        left: "%any"
        right: "{{ hostvars['cor-host-dmz'].ansible_ssh_host }}"
        rightsubnet: 192.168.11.0/24,192.168.3.0/24,192.168.4.0/24
        leftsubnet: 192.168.10.0/24,192.168.1.0/24,192.168.2.0/24
        leftid: "@frn-host-dmz"
        rightid: "@cor-host-dmz"
        ike: aes256-sha1-modp1024
        esp: aes256-sha1-modp1024
        auto: start
