# ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_ssh_common_args: >
  -o "ProxyCommand ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 
  -i {{ ansible_ssh_private_key_file }} centos@{{ bastion_ip }} nc  %h %p " 

# -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null